name: Build Mushaf APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. إعداد جافا 21
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # 2. إعداد نود 22
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # 3. تثبيت المكتبات
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # 4. بناء ملفات الويب
      - name: Build Web
        run: npm run build

      # 5. مزامنة كاباسيتور
      - name: Sync Capacitor
        run: npx cap sync android

      # 6. بناء الـ APK
      - name: Setup Gradle and Build
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2
          arguments: clean assembleDebug --no-daemon --stacktrace
          build-root-directory: android

      # 7. استخراج الملف النهائي
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mushaf-Al-Alaa-Debug
          path: android/app/build/outputs/apk/debug/*.apk